import UserContext from '../Context/UserContext';
import ThemeContext from '../Context/ThemeContext';
import '../styles/globals.scss';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return <ThemeContext>
          <UserContext>
            <Head>
                <title>Budget</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/x-icon" href="/favicon.png"/>
            </Head>
            <Component {...pageProps} />
          </UserContext>
        </ThemeContext>  
}

export default MyApp
