import Head from 'next/head'
import Home from '../components/Home/Home';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.png"/>
      </Head>
      <Home/>
    </>
  )
}
