import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import Home from '../components/Home/Home';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Budget</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Home/>
      </Layout>
    </>
  )
}
